### ISSUE TITLE
xmfa2fasta.pl doesn't notice lack of mafft binary

### ISSUE THREAD

**Issue by shadowcat-mst** [kjolley/seq_scripts#1]
Just had a user turn on to the perl-help IRC channel on irc.perl.org trying to run that script, and it turns out they don't have mafft installed yet.

Thing is, your code is using system() to call it without checking for errors, and the open doesn't fail because the redirect still manages to produce a 0 byte file with the correct name.

I'd suggest making at least one of three changes:

1) Change the call to system(...) == 0 or die "Failed to execute ${mafft}: $!"; # edited, I forgot the == 0
2) Checking -x on $mafft early on and bailing out if it fails
3) Making it possible to pass $mafft as an env var and/or on the command line in case it's installed but not in /usr/bin (possibly also using File::Which (which comes with perl already) to search $ENV{PATH} for the binary)

(note I have absolutely no idea about what your code does and how, these are "observations from a consultant who spends his life debugging other people's perl code" - free advice, worth exactly what you paid ;)

**Comment by kjolley** [comment]
Thanks! I'll fix this.
