### ISSUE TITLE
xmfa2fasta-- how does it work?

### ISSUE THREAD

**Issue by ravinpoudel** [kjolley/seq_scripts#2]
Is there a document with more information on how does xmfa2fasta.pl work?

**Comment by kjolley** [comment]
No, but if you run with --help option it tells you how to run it and what your options are.

**Comment by ravinpoudel** [comment]
@kjolley  thanks... I was able to run --help and implement the script. Thanks for providing/contributing the code. Is it possible to add little more on how the script does the job?  Is the fasta output the consensus read? Thanks in advance.

**Comment by kjolley** [comment]
It just reads through the XMFA file and adds each locus sequence to a separate buffer for each isolate. At the end it concatenates all the sequences for each isolate and exports these as separate sequence strings in a FASTA file.

When it reads in each locus block, it can optionally align all the sequences for the locus before adding them to their appropriate isolate buffer. This results in the whole concatenated sequence being aligned with the other records.

**Comment by ravinpoudel** [comment]
Thanks a lot @kjolley
