### ISSUE TITLE
Keep sequence name when using xmfa2fasta

### ISSUE THREAD

**Issue by quocviet0908** [kjolley/seq_scripts#3]
Hi.

I would like to keep the original name of each sequence to track them easier. Is there a way to do that?
I ran the script with both -i and not using -i but my sequence names keep convert to integers.

Thanks so much.

**Comment by kjolley** [comment]
Hello. It should keep the name - it does for me. Could you upload an example file to show where this isn't working?

**Comment by quocviet0908** [comment]
Hi.
This is my sample xmfa that I converted. I think the script takes the integers after ">" for the converted IDs and ignores the rest if there are non-integers characters like how the script stated. In this case, I guess it only kept 1 and 2 and everything after ":" was discarded.

> #FormatVersion Mauve1
> #Sequence1File	2201SEQ050_S30_L001_unicycler.fna
> #Sequence1Format	FastA
> #Sequence2File	NC_047930.fna
> #Sequence2Format	FastA
> > 1:1-41350 + 2201SEQ050_S30_L001_unicycler.fna
> ---------------------------------------------------------
> ....
> > 2:1-41135 + NC_047930.fna

**Comment by kjolley** [comment]
Could you upload the whole file please because I cannot see a valid XMFA file from what is copy/pasted above.

**Comment by kjolley** [comment]
However, if your header line is:

`>1:1-41350 + 2201SEQ050_S30_L001_unicycler.fna`

Then it is working as it should since anything after the : is the position.

**Comment by quocviet0908** [comment]
> However, if your header line is:
> 
> `>1:1-41350 + 2201SEQ050_S30_L001_unicycler.fna`
> 
> Then it is working as it should since anything after the : is the position.

Thank you for your quick response.
I'm sorry that I could not share the whole file because I'm not the data owner. But I think I can work around by manually replacing sequence identifiers.
